# Learn more about configuring your theme app extension at https://shopify.dev/docs/apps/app-extensions/theme-app-extensions

api_version = "2023-10"

[[extensions]]
type = "theme"
name = "Map App Extension"
handle = "map-app-extension"

[[extensions.metafields]]
namespace = "mapapp"
key = "store_locations"
type = "json"

[[extensions.metafields]]
namespace = "mapapp"
key = "map_settings"
type = "json"